# Generated by Django 4.2.7 on 2023-12-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actionvim", "0003_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="projects",
            field=models.ManyToManyField(
                through="actionvim.Permission", to="actionvim.project"
            ),
        ),
    ]
