# Generated by Django 4.2.7 on 2023-12-02 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("actionvim", "0006_project_task_count_project_task_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_permissions",
                to="actionvim.project",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
