# Generated by Django 4.2.7 on 2023-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actionvim", "0009_alter_section_project_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="task_count",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="public_id",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
