# Generated by Django 4.2.7 on 2023-12-04 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("actionvim", "0013_taskmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmember",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_members",
                to="actionvim.task",
            ),
        ),
    ]
