# Generated by Django 4.2.7 on 2023-12-04 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actionvim", "0014_alter_taskmember_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="members",
            field=models.ManyToManyField(
                through="actionvim.TaskMember", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
