# Generated by Django 5.2.5 on 2025-08-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("staff", "Staff"),
                    ("internal", "Internal"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
