# Generated by Django 5.2.5 on 2025-08-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superuser", "Superuser"),
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
