# Generated by Django 5.2.5 on 2025-08-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="source",
            field=models.CharField(default="web", max_length=64),
        ),
    ]
