# Generated by Django 5.2.5 on 2025-08-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="website",
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
