# Generated by Django 5.2.5 on 2025-08-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0002_setting_website"),
    ]

    operations = [
        migrations.RenameField(
            model_name="setting",
            old_name="contact_email",
            new_name="organization_contact_email",
        ),
        migrations.RenameField(
            model_name="setting",
            old_name="website",
            new_name="organization_website",
        ),
    ]
